### ISSUE TITLE
BACKEND Error: "cannot execute SQL commands in WAL sender for physical replication"

### ISSUE THREAD

**Issue by miguelconde91** [ubc/barman-docker#8]
Hello, I have an stack with two repmgr containers running and pgpool. If I connect barman directly to repmgr node 1 (running like primary) everything looks fine. However if I connect barman container with pgpool instead of repmgr directly this fails with this error:

Docker images in use:
ubcctlt/barman:v2.19
bitnami/postgresql-repmgr:13.6.0-debian-10-r78
bitnami/pgpool:4.3.1-debian-10-r68

```
Setting ownership/permissions on /var/lib/barman and /var/log/barman
Generating cron schedules
Generating Barman configurations
Checking/Creating replication slot
Creating physical replication slot 'barman' on server 'pgpool'
2022-05-11 19:53:18,625 [18] barman.server INFO: Creating physical replication slot 'barman' on server 'pgpool'
ERROR: Cannot create replication slot 'barman' on server 'pgpool': Backend throw an error message
DETAIL:  Exiting current session because of an error from backend
HINT:  BACKEND Error: "cannot execute SQL commands in WAL sender for physical replication"
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
2022-05-11 19:53:18,668 [18] barman.server ERROR: Cannot create replication slot 'barman' on server 'pgpool': Backend throw an error message
DETAIL:  Exiting current session because of an error from backend
HINT:  BACKEND Error: "cannot execute SQL commands in WAL sender for physical replication"
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
Nothing to do. Position of receive-wal is aligned.
2022-05-11 19:53:19,768 [21] barman.wal_archiver INFO: Nothing to do. Position of receive-wal is aligned.
Initializing done
Started Barman exporter on 0.0.0.0:9780
Exception in thread Thread-2:
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/barman -f json status pgpool

  STDOUT:
{"_EXCEPTION": ["Backend throw an error message\nDETAIL:  Exiting current session because of an error from backend\nHINT:  BACKEND Error: \"cannot execute SQL commands in WAL sender for physical replication\"\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\nSee log file for more details."], "pgpool": {"active": {"description": "Active", "message": "True"}, "description": {"description": "Description", "message": "PostgreSQL Database (Streaming-Only)"}, "disabled": {"description": "Disabled", "message": "False"}}}

  STDERR:
2022-05-11 19:53:21,124 [36] barman.cli ERROR: Backend throw an error message
DETAIL:  Exiting current session because of an error from backend
HINT:  BACKEND Error: "cannot execute SQL commands in WAL sender for physical replication"
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

See log file for more details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/barman/cli.py", line 1910, in main
    args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/barman/cli.py", line 510, in status
    server.status()
  File "/usr/local/lib/python3.9/dist-packages/barman/server.py", line 1230, in status
    self.status_pos... (1107 more, please see e.stderr)
```
My app is connected successfully to pgpool container. Why barman no? What is the difference bewteen use directly barman w/ pgpool & barman w/ repmgr or postgres.

**Comment by mennasheta** [comment]
have the same issue as well , any update ?

**Comment by xcompass** [comment]
Sorry, we are not using barman anymore. Seems like a bug with barman? Maybe you should post your message to barman community directly: https://pgbarman.org/support/

I've just also updated barman to 3.2.0. You can also give it a try to see if it solves the issue. Sorry, I can't test it as we don't have the infra anymore.

**Comment by AkashRajvanshi** [comment]
Hi, can you please share dockerfile or any config for barman with postgres 12/13 on docker, I tried to create tbeadle barman image with postgres 13 but getting error.

**Comment by xcompass** [comment]
The dockerfile is in this repo: https://github.com/ubc/barman-docker/blob/master/Dockerfile. It has postgres 12/13/14 client. So it should work with 13.

Please feel free to open a new issue with detailed error message if you need any help.
